spring:
  datasource:
    druid:
      url: jdbc:mysql://192.168.31.12:3306/blog_db?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: root
      password: Root_2019
      stat-view-servlet:
        login-username: admin
        login-password: admin
mybatis:
  mapper-locations: classpath:/mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
