server:
  port: 8080

# http://gateway_host:gateway_port/serviceId/**
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
#      routes:
#      - id: test
#        uri: lb://TEST/test
#        predicates:
#          - Path=/test
logging:
  level:
    org.springframework.cloud.gateway: trace
    org.springframework.http.server.reactive: debug
    org.springframework.web.reactive: debug
    reactor.ipc.netty: debug

feign:
  hystrix:
    enabled: true

hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000
