spring:
  application:
    name: test
  rabbitmq:
    host: 192.168.31.12
    port: 5672
    username: evan
    password: 123456
    virtualHost: /
    publisherConfirms: true

server:
#  port: 9998
  port: 9999

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    healthcheck:
      enabled: true
    register-with-eureka: true
    fetch-registry: true

data:
  message: 'message'

management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info


