spring:
  application:
    name: test
  rabbitmq:
    host: 192.168.31.12
    port: 5672
    username: evan
    password: 123456
    virtualHost: /
    publisherConfirms: true

server:
  port: 9999
eureka:
  client:
    healthcheck:
      enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://admin:admin123@localhost:8100/eureka/
#data:
#  message: test1
#management:
#  endpoints:
#    web:
#      exposure:
#        include: refresh,health,info


